### ISSUE TITLE
Markdown oder R Markdown oder vielleicht Rmarkdown?

### ISSUE THREAD

**Issue by NMarkgraf** [FOM-ifes/StudentGuide-mosaic#1]
Hallo liebe StudendGuider,

danke noch einmal für die Arbeit und Mühe mit der Übersetzung. Ich finde das Werk sehr gelungen. Aber, wie immer, schleichen sich in jedes Projekt ab und zu kleinere Unschönheiten ein.

Von einer möchte ich hier berichten und Fragen, wie es damit aussieht ob und wenn ja wer hier Korrekturen am Text machen darf, soll bzw. kann.

Auf der Seite 9 und später auf der Seite 11 schreibt Ihr "Markdown", wo ich mir ziemlich sicher bin, dass es "RMarkdown" seien sollte. Insbesondere bei der Bezeichnung von R-Paketen, sollte mensch darauf achten den Namen des Paktes richtig zu schreiben.
Es gibt nämlich beide Pakete, die durchaus unterschiedlich arbeiten!

-> https://github.com/rstudio/markdown
-> https://github.com/rstudio/rmarkdown

Weiterhin wird im Text mal von RMarkdown, dann wieder von R Markdown gesprochen. Ich denke die Eigenschreibweise ist Rmarkdown, sollte mensch sich vielleicht daran orientieren?

Viele Grüße
Norman Markgraf

**Comment by Bia-Ka** [comment]
Lieber Norman, danke für das aufmerksame Lesen und die Hinweise. Bestimmt findet sich noch mehr - wir immer bei solchen Werken gibt es Optimierungspotenzial (auch im Hinblick auf das 2. issue). 

> wie es damit aussieht ob und wenn ja wer hier Korrekturen am Text machen darf, soll bzw. kann

Das wiederum ist eine gute Frage. Vielleicht könnte @TabeaG die Dinge einarbeiten? Das bespreche ich mal mit ihr. ;-) 
Eigentlich würde ich ja sagen, wer den Fehler findet, darf einfach korrigieren und alle würden sich freuen. Das gilt für die von mir übersetzten Textteile auf jeden Fall. Ich kann aber nicht so richtig abschätzen, ob das jede(r) so sieht. Weiß jemand, ob es dabei Regeln zu beachten gilt (cc, Urheber...)???

**Comment by Bia-Ka** [comment]
... warum kann ich hier nur einen Menschen assignen? Ich wollte @TabeaG nicht rauswerfen und eigentlich wollte ich @TanjaKistler  auch noch hier aufnehmen.

**Comment by NMarkgraf** [comment]
> ... warum kann ich hier nur einen Menschen assignen? Ich wollte @TabeaG nicht rauswerfen und eigentlich wollte ich @TanjaKistler auch noch hier aufnehmen.

Das ist leider ein neues Feature, damit Du in Zukunft 40$ pro Jahr zahlst um mehr als 1 Person zu assignen ...

https://docs.github.com/en/get-started/learning-about-github/faq-about-changes-to-githubs-plans#if-i-downgrade-from-github-team-or-a-legacy-plan-to-github-free-what-features-will-i-lose

**Comment by NMarkgraf** [comment]
Liebe Bianca,

> > wie es damit aussieht ob und wenn ja wer hier Korrekturen am Text machen darf, soll bzw. kann
> 
> Das wiederum ist eine gute Frage. 

soll das heissen, meine erste Frage war keine gute Frage? :-P


> Vielleicht könnte @TabeaG die Dinge einarbeiten? Das bespreche ich mal mit ihr. ;-) 

Fände ich eine gute Idee, alleine schon um eine gewisse Struktur reinzubekommen und nicht wieder tausend Hände und kein Ende ...

>Eigentlich würde ich ja sagen, wer den Fehler findet, darf einfach korrigieren und alle würden sich freuen. 

Damit könnte ich persönlich auch leben.

> Das gilt für die von mir übersetzten Textteile auf jeden Fall. 

> Ich kann aber nicht so richtig abschätzen, ob das jede(r) so sieht. Weiß jemand, ob es dabei Regeln zu beachten gilt (cc, Urheber...)???

Nun der gesamte Text ist unter CC, wenn ich das richtig sehe und daher so oder so von jeden veränderbar. 

> Copyright (c) 2015 by Nicholas J. Horton, Randall Pruim, & Daniel Kaplan.
Edition 1.2, November 2015
This material is copyrighted by the authors under a Creative Commons Attribution 3.0 Unported License. You are free to Share (to copy, distribute and transmit the work) and to Remix (to adapt the work) if you attribute our work. More detailed information about the licensing is available at this web page: http: //www.mosaic-web.org/go/teachingRlicense.html.

Leider liegt aber auch genau da "euer" Problem. Denn ihr habt eigentlich, so wie es im Original steht, eine Urheberrechtsverletzung begangen, weil ich genau diese Zeilen da oben eben gerade NICHT in dem Text habt. 

Vorschlag:

- Wir passen den Text bzgl der Copyrights in der deutschen Fassung entsprechend an
- Wir geben danach das Repsoitory als PUBLIC frei (!), aber lassen Änderungen von 3. nur per Pull-Request zu. Gemäß der CC 3.0 oder 4.0 (was ich sagen würde) als

**Comment by Bia-Ka** [comment]
Lieber @NMarkgraf , das finde ich einen guten Vorschlag (und selbstverständlich war auch die erste Frage gut). @TabeaG , könntest du die Urheberrechtsverletzung hier heilen - vielleicht kann Norman einen bilateralen Tipp geben, damit das rechtlich alles seine Richtigkeit hat? 
@TabeaG , könntest du auch den Punkt zwei danach übernehmen / koordinieren (Public-Zugang, Pull-Request-Zulassung)? Dann müsste auch in unseren MSB noch die Version ausgetauscht werden.
Ich würde mich dann darum kümmern, dass die berichtigte Unterlage in den allgemeinen Downloadbereich der FOM kommt (das könnte leider der schwierigere Teil der Aufgaben sein, wenn ich da an unseren OC denke...)
Schon einmal vielen Dank. :-)

**Comment by NMarkgraf** [comment]
Liebe @Bia-Ka ,
liebe @TabeaG ,

ich denke das Problem ist, dass ich mir nicht sicher bin welches CC genau die haben. Ich tippe mal auf CC 3.0 BY-SA, aber sicher weiß ich es nicht und die WebSeite auf der es stehen sollte ist nicht mehr aktiv. Anfrage läuft schon ...

Es wäre nämlich schön wenn wir das von CC 3.0 auf CC 4.0 updaten könnten im dem Kontext. Das würde allen (auch den Original-Autoren) sicher behilflich sein. 

Viele Grüße in diesen Zeiten,
Norman

**Comment by TabeaG** [comment]
Die "inhaltlichen" Punkte und die Erwähnung der Lizenz sind erledigt. 

Punkt 2 kann ich nicht übernehmen, da ich - nachdem ich auf FOMifes verschoben habe - nicht mehr die Option angezeigt bekomme auf Public stellen zu können. Vermutlich habe ich hier die Berechtigungen nicht dazu?!

**Comment by NMarkgraf** [comment]
@TabeaG ,ab  jetzt solltest Du auch diese Rechte haben! :-)

**Comment by TabeaG** [comment]
Danke! Repo ist jetzt Public (und in den MSBs ist das PDF hier verlinkt).
